[package]
name = "codegen"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
thiserror = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
quick-xml = { version = "0.36", features = [ "serialize" ] }
shared = { path = "../shared" }